#!/usr/bin/env bash
#Bash script to install nginx web server returning a page from querie
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart
