#!/usr/bin/env bash
#Bash script to install nginx web server returning a page from querie

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
