#!/usr/bin/env bash
# This is a Bash script that displays the PID, 
# along with the process name, of processes whose name contain the word bash

str="To infinity and beyond"
while ((i>=0)); 
do 
	echo "$str"
	((i++))
	trap "echo I am invincible!!!" SIGTERM
	sleep 2
done
