#!/usr/bin/env bash
# This is a Bash script that displays:
# To infinity and beyond indefinitely
# With a sleep 2 in between each iteration
# I am invincible!!! when receiving a SIGTERM signal


str="To infinity and beyond"
while ((i>=0)); 
do 
	echo "$str"
	((i++))
	trap "echo I am invincible!!!" SIGTERM
	sleep 2
done
