#!/usr/bin/env bash
# This script is a Bash script that displays the content of the file /etc/passwd.
# only display: username, user id and Home directory path for the user

LIST='/etc/passwd'
while read -r line;
do
	echo "$line" | cut -d ":" -f1,3,6
done < "$LIST"
