#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and "Hi" in 9nth Position with while loop

LIST="Holberton School"
i=0
while ((i<10)); 
	do 
		echo "$LIST"
	((i++))
	if [ $i = 9 ]; 
	then 
		echo "Hi"
	fi
done
