#!/usr/bin/env bash
# This script is a Bash script that gives you information about the holbertonschool file

FILE=holbertonschool
if test -e "$FILE"; 
then 
	echo "$FILE file exists"
	if test -f "$FILE";
	then
		echo "$FILE is a regular file"
	fi
	if test -s "$FILE";
	then
		echo "$FILE file is not empty"
	else
		echo "$FILE file is empty"
	fi
else
	echo "$FILE file does not exist"
fi
