#!/usr/bin/env bash
#Script to make Apache to run on the container and to return a page
#containing Hello Holberton when querying the root of it.
docker run -p 8080:80 -d -it holbertonschool/265-0
echo Hello Holberton > holbertonschool/265-0
