#!/usr/bin/env bash
#Bash script to fix a container so that Nginx is running as the nginx user.
pkill -f apache2
chown nginx:nginx /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chmod 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
